// Generated from official/public brand assets plus user-provided brand artwork.
// Dimensions are intrinsic source dimensions and are used only to size logo tiles.
export const brandLogoAssets: Record<string, { file: string; width: number; height: number }> = {
  alfamart: { file: "alfamart.png", width: 600, height: 600 },
  alfamidi: { file: "alfamidi.svg", width: 200, height: 80 },
  anteraja: { file: "anteraja.svg", width: 200, height: 80 },
  "ayam-geprek-sai": { file: "ayam-geprek-sai.webp", width: 360, height: 360 },
  "baba-rafi": { file: "baba-rafi.png", width: 600, height: 300 },
  bingxue: { file: "bingxue-user.webp", width: 560, height: 221 },
  "doyan-ayam": { file: "doyan-ayam.webp", width: 496, height: 560 },
  "es-teh-indonesia": { file: "esteh-indonesia.svg", width: 280, height: 96 },
  "teh-poci": { file: "esteh-poci.png", width: 600, height: 600 },
  familymart: { file: "familymart.svg", width: 200, height: 80 },
  "geprek-bensu": { file: "geprek-bensu.webp", width: 360, height: 274 },
  indomaret: { file: "indomaret.svg", width: 200, height: 80 },
  "janji-jiwa": { file: "janji-jiwa.webp", width: 560, height: 488 },
  jne: { file: "jne.svg", width: 200, height: 80 },
  jnt: { file: "jnt-express.webp", width: 560, height: 393 },
  kopigo: { file: "kopigo.svg", width: 512, height: 512 },
  lawson: { file: "lawson.svg", width: 200, height: 80 },
  "lion-parcel": { file: "lion-parcel.svg", width: 200, height: 80 },
  "mr-klin": { file: "mr-klin.webp", width: 560, height: 208 },
  "ninja-xpress": { file: "ninja-xpress.svg", width: 200, height: 80 },
  "nyoklat-klasik": { file: "nyoklat-klasik.webp", width: 560, height: 179 },
  omi: { file: "omi.svg", width: 200, height: 80 },
  "point-coffee": { file: "point-coffee.webp", width: 360, height: 255 },
  sabana: { file: "sabana.webp", width: 560, height: 202 },
  sicepat: { file: "sicepat.svg", width: 200, height: 80 },
  "tahu-go": { file: "tahu-go.webp", width: 560, height: 528 },
  wahana: { file: "wahana.svg", width: 200, height: 80 },
  yomart: { file: "yomart.svg", width: 200, height: 80 },

  // Researched/localized assets added for brands that previously hotlinked or
  // fell back to initials. These stay local so cards remain stable.
  basmalah: { file: "basmalah-mart.png", width: 640, height: 240 },
  "212-mart": { file: "212-mart.jpg", width: 640, height: 360 },
  haus: { file: "haus.jpg", width: 640, height: 360 },
  hisana: { file: "hisana.jpg", width: 640, height: 360 },
  dbesto: { file: "dbesto.jpg", width: 640, height: 360 },
  "rocket-chicken": { file: "rocket-chicken.png", width: 640, height: 240 },
  "apotek-f21": { file: "apotek-f21.svg", width: 640, height: 240 },
  "griya-farma": { file: "griya-farma.jpg", width: 640, height: 360 },
  "century-pharma": { file: "century-pharma.png", width: 600, height: 600 },
  "kimia-farma": { file: "kimia-farma.jpg", width: 640, height: 360 },
  pasfarma: { file: "pasfarma.jpg", width: 640, height: 360 },
  "optik-loka": { file: "optik-loka.jpg", width: 640, height: 360 },
  "viva-generik": { file: "viva-generik.jpg", width: 640, height: 360 },
  farmapoint: { file: "farmapoint.jpg", width: 640, height: 360 },
  "optik-melawai": { file: "optik-melawai.jpg", width: 640, height: 360 },
};
