import type { InputKey } from "./engine";
export const labels: Record<InputKey, string> = {
  units: "Volume per periode",
  ticket: "Harga / basket / ongkir rata-rata",
  days: "Hari operasi per bulan",
  commissionRate: "Komisi (rasio)",
  commissionFixed: "Komisi Rp per paket",
  cogsRate: "HPP (rasio)",
  unitCost: "Biaya variabel Rp per unit",
  employees: "Jumlah staf",
  salary: "Gaji per staf / bulan",
  payrollLoad: "Cadangan benefit (rasio)",
  ownerPay: "Kompensasi pemilik / bulan",
  rent: "Sewa / bulan",
  utilities: "Utilitas / bulan",
  logistics: "Logistik / bulan",
  marketing: "Marketing / bulan",
  maintenance: "Maintenance / bulan",
  other: "Biaya lainnya / bulan",
  royaltyRate: "Royalti (rasio)",
  recurringFee: "Biaya sistem / bulan",
  profitShare: "Bagi laba positif (rasio)",
  equipment: "Peralatan / paket setup",
  fitout: "Renovasi / instalasi",
  entryFee: "Fee awal",
  deposit: "Deposit",
  inventory: "Stok awal",
  reserveMonths: "Cadangan biaya tetap (bulan)",
  taxReserve: "Cadangan pajak laba (rasio)",
  debtService: "Cicilan / bulan",
  replacementReserve: "Cadangan penggantian aset / bulan",
};
export const evidenceLabels = {
  official: "OFFICIAL",
  verified: "VERIFIED THIRD-PARTY",
  estimate: "CEK BISNIS ESTIMATE",
  unknown: "UNKNOWN",
};
